theme = "PaperMod"
baseURL = "https://d1i59hjyx64k6h.cloudfront.net"
title = "Ashish DevOps Blog"

[params]
  ShowReadingTime = true
  ShowShareButtons = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
